# Generated by Django 4.2.4 on 2023-09-26 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='firts_name',
            new_name='first_name',
        ),
    ]
